#include <iostream>
#include <ctime> // Needed to access the system clock

int main() {
    // Seed the random number generator using the current time so the result is different every run
    srand(time(NULL)); 

    // rand() % 6 gives a number from 0 to 5. Adding 1 changes the range to 1-6.
    int num = (rand() % 6 + 1); 

    // Print the random number to the console
    std::cout << num << "\n"; 
}


/*we'll generate "pseudo random" number using the header file "<ctime>"
pseudo random number: a number that appears to be random but is generated by a
 deterministic process */